services:
  - type: web
    name: mining-dashboard
    runtime: python
    branch: dev
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server --workers 2
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
